-- Seed data imported from client-list.xlsx
INSERT INTO clients (ma, ten_khach_hang, ten_day_du, mst, dia_chi, nguoi_dai_dien, chuc_danh, lien_he, trang_thai) VALUES
('ADMP', 'ADM Promotions', 'CÔNG TY TNHH ADM PROMOTIONS VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('AVNV', 'Ajinomoto Việt Nam', 'CÔNG TY AJINOMOTO VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('ALAV', 'Alavita Master Blod', NULL, NULL, NULL, NULL, NULL, '{}', 'Disable'),
('ALOK', 'Alo Khifa', NULL, NULL, NULL, NULL, NULL, '{}', 'Disable'),
('AMKB', 'Amavi Kombucha', 'CÔNG TY CỔ PHẦN AMAVI KOMBUCHA', NULL, NULL, NULL, NULL, '{}', 'Active'),
('AMWV', 'Amway Việt Nam', 'CÔNG TY TNHH AMWAY VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('BSHX', 'BSH', 'CÔNG TY TNHH ĐỒ GIA DỤNG BSH (VIỆT NAM)', NULL, NULL, NULL, NULL, '{}', 'Active'),
('BEGR', 'Be Group', 'CÔNG TY CỔ PHẦN BE GROUP', NULL, NULL, NULL, NULL, '{}', 'Active'),
('BFNX', 'Befinacial', 'CÔNG TY TNHH BEFINACIAL', NULL, NULL, NULL, NULL, '{}', 'Active'),
('BTRX', 'Betrimex', 'CÔNG TY CỔ PHẦN XUẤT NHẬP KHẨU BẾN TRE', NULL, NULL, NULL, NULL, '{}', 'Active'),
('BLSC', 'BlueScope VN', 'CÔNG TY TNHH NS BLUESCOPE VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('BLSD', 'BlueSeed', 'CÔNG TY CỔ PHẦN BLUESEED', NULL, NULL, NULL, NULL, '{}', 'Active'),
('CATA', 'CARTA VIỆT NAM', 'CÔNG TY TNHH CARTA VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('CETA', 'CETAPHIL', 'CÔNG TY TNHH GALDERMA VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('CRLS', 'Carlsberg', 'CÔNG TY TNHH BIA CARLSBERG VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('CPSH', 'CellphoneS HCM', 'CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ KỸ THUẬT DIỆU PHÚC', NULL, NULL, NULL, NULL, '{}', 'Active'),
('CPHN', 'CellphoneS HN', 'CÔNG TY TNHH THƯƠNG MẠI TỔNG HỢP HTV', NULL, NULL, NULL, NULL, '{}', 'Active'),
('CCVN', 'Coca-Cola VN', 'CÔNG TY TNHH NƯỚC GIẢI KHÁT COCA-COLA VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('COOM', 'Coo Mel', NULL, NULL, NULL, NULL, NULL, '{}', 'Active'),
('CTNC', 'Cotana Capital', 'CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ PHÁT TRIỂN BẤT ĐỘNG SẢN COTANA CAPITAL', NULL, NULL, NULL, NULL, '{}', 'Active'),
('DSPV', 'DENTSU SPORT', 'CÔNG TY TNHH DENTSU SPORTS VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('DHGG', 'Dược Hậu Giang', 'CÔNG TY CỔ PHẦN DƯỢC HẬU GIANG', NULL, NULL, NULL, NULL, '{}', 'Active'),
('galderma-vn', 'GALDERMA VN', NULL, NULL, NULL, NULL, NULL, '{}', 'Active'),
('GAVX', 'GAV Việt Nam', 'CÔNG TY TNHH THƯƠNG MẠI GAV VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('HAFL', 'Hafele Việt Nam', 'CÔNG TY TNHH HAFELE VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('HNKX', 'Hankook Vina', 'CÔNG TY TNHH HAN KOOK-VINA EMB', NULL, NULL, NULL, NULL, '{}', 'Active'),
('HEIN', 'Heineken Việt Nam', 'CÔNG TY TNHH NHÀ MÁY BIA HEINEKEN VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('HHCM', 'HiteJinro HCM', 'CHI NHÁNH CÔNG TY TNHH HITEJINRO VIỆT NAM TẠI THÀNH PHỐ HỒ CHÍ MINH', NULL, NULL, NULL, NULL, '{}', 'Active'),
('HTJR', 'HiteJinro Việt Nam', 'CÔNG TY TNHH HITEJINRO VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('HYND', 'Hyundai', 'CÔNG TY CỔ PHẦN LIÊN DOANH Ô TÔ HYUNDAI THÀNH CÔNG VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('kido', 'KIDO', 'CÔNG TY CỔ PHẦN TẬP ĐOÀN KIDO', NULL, NULL, NULL, NULL, '{}', 'Active'),
('LWWN-2', 'LIWAYWAY', 'CÔNG TY TNHH CÔNG NGHIỆP THỰC PHẨM LIWAYWAY SÀI GÒN', NULL, NULL, NULL, NULL, '{}', 'Active'),
('LOFM', 'LOF Milk', 'CÔNG TY CỔ PHẦN SỮA QUỐC TẾ LOF', NULL, NULL, NULL, NULL, '{}', 'Active'),
('LWWS', 'Liwayway SG', 'CÔNG TY TNHH CÔNG NGHIỆP THỰC PHẨM LIWAYWAY SÀI GÒN', NULL, NULL, NULL, NULL, '{}', 'Active'),
('MSVC', 'MSV Marketing', 'CÔNG TY TƯ VẤN PHÁT TRIỂN THỊ TRƯỜNG M.S.V', NULL, NULL, NULL, NULL, '{}', 'Active'),
('MSAN', 'Masan Consumer', 'CÔNG TY CỔ PHẦN HÀNG TIÊU DÙNG MASAN', NULL, NULL, NULL, NULL, '{}', 'Active'),
('MINT', 'Minthacare', 'CÔNG TY TNHH MINTHACARE', NULL, NULL, NULL, NULL, '{}', 'Active'),
('MDHG', 'Mowin Digital Holdings', 'CÔNG TY TNHH MOWIN DIGITAL HOLDINGS', NULL, NULL, NULL, NULL, '{}', 'Active'),
('NSTL', 'Nestlé Việt Nam', 'CÔNG TY TNHH NESTLÉ VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('NVLD', 'Novaland', 'CÔNG TY CỔ PHẦN TẬP ĐOÀN ĐẦU TƯ ĐỊA ỐC NO VA', NULL, NULL, NULL, NULL, '{}', 'Active'),
('OPVK', 'OPPO – Vĩnh Khang', 'CÔNG TY CỔ PHẦN KỸ THUẬT & KHOA HỌC VĨNH KHANG', NULL, NULL, NULL, NULL, '{}', 'Active'),
('OUTC', 'Outcome Marketing', 'CÔNG TY TNHH OUTCOME MARKETING', NULL, NULL, NULL, NULL, '{}', 'Active'),
('P2PC', 'P2P Marketing', 'CÔNG TY TNHH TRUYỀN THÔNG TIẾP THỊ P2P', NULL, NULL, NULL, NULL, '{}', 'Active'),
('PWCV', 'PWC VN (HCM)', 'CÔNG TY TNHH PWC (VIỆT NAM)', NULL, NULL, NULL, NULL, '{}', 'Active'),
('PEPS', 'Pepsico VN', 'CÔNG TY TNHH NƯỚC GIẢI KHÁT SUNTORY PEPSICO VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('PFVM', 'Perfetti Van Melle (Viet Nam)', NULL, NULL, NULL, NULL, NULL, '{}', 'Active'),
('PRCD', 'Pernod Ricard', 'CÔNG TY TNHH RƯỢU VÀ ĐỒ UỐNG CÓ CỒN PERNOD RICARD VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('PHUL', 'Phú Long', 'CÔNG TY CỔ PHẦN ĐỊA ỐC PHÚ LONG', NULL, NULL, NULL, NULL, '{}', 'Active'),
('SHEL', 'Shell Việt Nam', 'CÔNG TY SHELL VIỆT NAM TRÁCH NHIỆM HỮU HẠN', NULL, NULL, NULL, NULL, '{}', 'Active'),
('SNBR', 'SunBright', 'CÔNG TY CỔ PHẦN SÁNG TẠO NGHỆ THUẬT VÀ SỰ KIỆN SUN BRIGHT', NULL, NULL, NULL, NULL, '{}', 'Active'),
('SWBY', 'Swanbay', 'CÔNG TY CỔ PHẦN VINA ĐẠI PHƯỚC', NULL, NULL, NULL, NULL, '{}', 'Active'),
('SWCY', 'Swancity', 'CÔNG TY CỔ PHẦN ĐẠI PHƯỚC SWANCITY ONE MEA', NULL, NULL, NULL, NULL, '{}', 'Active'),
('TCPT', 'TCP Thailand', 'T.C.PHARMACEUTICAL INDUSTRIES CO., LT', NULL, NULL, NULL, NULL, '{}', 'Active'),
('THML', 'TH Milk', 'CÔNG TY CỔ PHẦN CHUỖI THỰC PHẨM TH', NULL, NULL, NULL, NULL, '{}', 'Active'),
('TNVN', 'Trung Nguyên', 'CÔNG TY CỔ PHẦN TẬP ĐOÀN TRUNG NGUYÊN', NULL, NULL, NULL, NULL, '{}', 'Active'),
('UOBX', 'UOB Việt Nam', 'NGÂN HÀNG TNHH MỘT THÀNH VIÊN UNITED OVERSEAS BANK (VIỆT NAM)', NULL, NULL, NULL, NULL, '{}', 'Active'),
('USSC', 'Umbrella Corporation', 'Công ty Khoa học kĩ thuật và công nghệ sinh học Umbrella', '7245689984-UC', NULL, NULL, NULL, '{}', 'Active'),
('UNBN', 'Uniben', 'CÔNG TY CỔ PHẦN UNIBEN', NULL, NULL, NULL, NULL, '{}', 'Active'),
('VINA', 'VINA EMB', 'CÔNG TY TNHH HAN KOOK-VINA EMB', NULL, NULL, NULL, NULL, '{}', 'Active'),
('VNFS', 'VinFast', 'CÔNG TY TNHH KINH DOANH THƯƠNG MẠI VÀ DỊCH VỤ VINFAST', NULL, NULL, NULL, NULL, '{}', 'Active'),
('VNMK', 'Vinamilk', 'CÔNG TY CỔ PHẦN SỮA VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('VDVN', 'Vita Diary', 'CÔNG TY CỔ PHẦN SỮA VITADAIRY VIỆT NAM', NULL, NULL, NULL, NULL, '{}', 'Active'),
('WATS', 'Watsons', 'CÔNG TY TNHH WATSONS (VIỆT NAM)', NULL, NULL, NULL, NULL, '{}', 'Active')
ON CONFLICT (ma) DO NOTHING;
